welcome = mkstr("**************************\n**  Welcome To D^3CTF   **\n**   Ancient Game V2    **\n**************************\n\nInput Flag:")
wrong = mkstr("\nSorry, please try again.\n")
correct = mkstr("\nCorrect.\n")

flag = new(50)
// distract = new(1000)
grid = new(81)


// initial puzzle
set(grid[0],9)
set(grid[5],8)
set(grid[9],1)
set(grid[10],3)
set(grid[14],9)
set(grid[16],7)
set(grid[17],2)
set(grid[19],5)
set(grid[20],2)
set(grid[25],8)
set(grid[26],3)
set(grid[28],2)
set(grid[29],4)
set(grid[31],1)
set(grid[32],6)
set(grid[40],9)
set(grid[48],8)
set(grid[49],7)
set(grid[51],2)
set(grid[52],5)
set(grid[54],7)
set(grid[55],8)
set(grid[60],5)
set(grid[61],2)
set(grid[63],5)
set(grid[64],1)
set(grid[66],7)
set(grid[70],4)
set(grid[71],6)
set(grid[75],9)
set(grid[80],1)

data_insert_junk
data_shuffle

__code_start__

// print the welcome message
print(welcome)

// get input
input(flag[0])
input(flag[1])
input(flag[2])
input(flag[3])
input(flag[4])
input(flag[5])
input(flag[6])
input(flag[7])
input(flag[8])
input(flag[9])
input(flag[10])
input(flag[11])
input(flag[12])
input(flag[13])
input(flag[14])
input(flag[15])
input(flag[16])
input(flag[17])
input(flag[18])
input(flag[19])
input(flag[20])
input(flag[21])
input(flag[22])
input(flag[23])
input(flag[24])
input(flag[25])
input(flag[26])
input(flag[27])
input(flag[28])
input(flag[29])
input(flag[30])
input(flag[31])
input(flag[32])
input(flag[33])
input(flag[34])
input(flag[35])
input(flag[36])
input(flag[37])
input(flag[38])
input(flag[39])
input(flag[40])
input(flag[41])
input(flag[42])
input(flag[43])
input(flag[44])
input(flag[45])
input(flag[46])
input(flag[47])
input(flag[48])
input(flag[49])

// In order to increase tracing difficulty, 
// use a long path to transfer the flag into the grid.

long_transfer(flag[0],grid[1])
long_transfer(flag[1],grid[2])
long_transfer(flag[2],grid[3])
long_transfer(flag[3],grid[4])
long_transfer(flag[4],grid[6])
long_transfer(flag[5],grid[7])
long_transfer(flag[6],grid[8])
long_transfer(flag[7],grid[11])
long_transfer(flag[8],grid[12])
long_transfer(flag[9],grid[13])
long_transfer(flag[10],grid[15])
long_transfer(flag[11],grid[18])
long_transfer(flag[12],grid[21])
long_transfer(flag[13],grid[22])
long_transfer(flag[14],grid[23])
long_transfer(flag[15],grid[24])
long_transfer(flag[16],grid[27])
long_transfer(flag[17],grid[30])
long_transfer(flag[18],grid[33])
long_transfer(flag[19],grid[34])
long_transfer(flag[20],grid[35])
long_transfer(flag[21],grid[36])
long_transfer(flag[22],grid[37])
long_transfer(flag[23],grid[38])
long_transfer(flag[24],grid[39])
long_transfer(flag[25],grid[41])
long_transfer(flag[26],grid[42])
long_transfer(flag[27],grid[43])
long_transfer(flag[28],grid[44])
long_transfer(flag[29],grid[45])
long_transfer(flag[30],grid[46])
long_transfer(flag[31],grid[47])
long_transfer(flag[32],grid[50])
long_transfer(flag[33],grid[53])
long_transfer(flag[34],grid[56])
long_transfer(flag[35],grid[57])
long_transfer(flag[36],grid[58])
long_transfer(flag[37],grid[59])
long_transfer(flag[38],grid[62])
long_transfer(flag[39],grid[65])
long_transfer(flag[40],grid[67])
long_transfer(flag[41],grid[68])
long_transfer(flag[42],grid[69])
long_transfer(flag[43],grid[72])
long_transfer(flag[44],grid[73])
long_transfer(flag[45],grid[74])
long_transfer(flag[46],grid[76])
long_transfer(flag[47],grid[77])
long_transfer(flag[48],grid[78])
long_transfer(flag[49],grid[79])

// xor

grid[1] = grid[1] ^ xor_table[0]
grid[2] = grid[2] ^ xor_table[1]
grid[3] = grid[3] ^ xor_table[2]
grid[4] = grid[4] ^ xor_table[3]
grid[6] = grid[6] ^ xor_table[4]
grid[7] = grid[7] ^ xor_table[5]
grid[8] = grid[8] ^ xor_table[6]
grid[11] = grid[11] ^ xor_table[7]
grid[12] = grid[12] ^ xor_table[8]
grid[13] = grid[13] ^ xor_table[9]
grid[15] = grid[15] ^ xor_table[10]
grid[18] = grid[18] ^ xor_table[11]
grid[21] = grid[21] ^ xor_table[12]
grid[22] = grid[22] ^ xor_table[13]
grid[23] = grid[23] ^ xor_table[14]
grid[24] = grid[24] ^ xor_table[15]
grid[27] = grid[27] ^ xor_table[16]
grid[30] = grid[30] ^ xor_table[17]
grid[33] = grid[33] ^ xor_table[18]
grid[34] = grid[34] ^ xor_table[19]
grid[35] = grid[35] ^ xor_table[20]
grid[36] = grid[36] ^ xor_table[21]
grid[37] = grid[37] ^ xor_table[22]
grid[38] = grid[38] ^ xor_table[23]
grid[39] = grid[39] ^ xor_table[24]
grid[41] = grid[41] ^ xor_table[25]
grid[42] = grid[42] ^ xor_table[26]
grid[43] = grid[43] ^ xor_table[27]
grid[44] = grid[44] ^ xor_table[28]
grid[45] = grid[45] ^ xor_table[29]
grid[46] = grid[46] ^ xor_table[30]
grid[47] = grid[47] ^ xor_table[31]
grid[50] = grid[50] ^ xor_table[32]
grid[53] = grid[53] ^ xor_table[33]
grid[56] = grid[56] ^ xor_table[34]
grid[57] = grid[57] ^ xor_table[35]
grid[58] = grid[58] ^ xor_table[36]
grid[59] = grid[59] ^ xor_table[37]
grid[62] = grid[62] ^ xor_table[38]
grid[65] = grid[65] ^ xor_table[39]
grid[67] = grid[67] ^ xor_table[40]
grid[68] = grid[68] ^ xor_table[41]
grid[69] = grid[69] ^ xor_table[42]
grid[72] = grid[72] ^ xor_table[43]
grid[73] = grid[73] ^ xor_table[44]
grid[74] = grid[74] ^ xor_table[45]
grid[76] = grid[76] ^ xor_table[46]
grid[77] = grid[77] ^ xor_table[47]
grid[78] = grid[78] ^ xor_table[48]
grid[79] = grid[79] ^ xor_table[49]


// verify the sudoku game

// rows
jmp _label_wrong if grid[4] == grid[5]
jmp _label_wrong if grid[4] == grid[6]
jmp _label_wrong if grid[4] == grid[7]
jmp _label_wrong if grid[4] == grid[8]
jmp _label_wrong if grid[5] == grid[6]
jmp _label_wrong if grid[5] == grid[7]
jmp _label_wrong if grid[5] == grid[8]
jmp _label_wrong if grid[6] == grid[7]
jmp _label_wrong if grid[6] == grid[8]
jmp _label_wrong if grid[7] == grid[8]
jmp _label_wrong if grid[9] == grid[10]
jmp _label_wrong if grid[9] == grid[11]
jmp _label_wrong if grid[9] == grid[12]
jmp _label_wrong if grid[9] == grid[13]
jmp _label_wrong if grid[9] == grid[14]
jmp _label_wrong if grid[9] == grid[15]
jmp _label_wrong if grid[9] == grid[16]
jmp _label_wrong if grid[9] == grid[17]
jmp _label_wrong if grid[10] == grid[11]
jmp _label_wrong if grid[10] == grid[12]
jmp _label_wrong if grid[10] == grid[13]
jmp _label_wrong if grid[10] == grid[14]
jmp _label_wrong if grid[10] == grid[15]
jmp _label_wrong if grid[10] == grid[16]
jmp _label_wrong if grid[10] == grid[17]
jmp _label_wrong if grid[11] == grid[12]
jmp _label_wrong if grid[11] == grid[13]
jmp _label_wrong if grid[11] == grid[14]
jmp _label_wrong if grid[11] == grid[15]
jmp _label_wrong if grid[11] == grid[16]
jmp _label_wrong if grid[11] == grid[17]
jmp _label_wrong if grid[12] == grid[13]
jmp _label_wrong if grid[12] == grid[14]
jmp _label_wrong if grid[12] == grid[15]
jmp _label_wrong if grid[12] == grid[16]
jmp _label_wrong if grid[12] == grid[17]
jmp _label_wrong if grid[13] == grid[14]
jmp _label_wrong if grid[13] == grid[15]
jmp _label_wrong if grid[13] == grid[16]
jmp _label_wrong if grid[13] == grid[17]
jmp _label_wrong if grid[14] == grid[15]
jmp _label_wrong if grid[14] == grid[16]
jmp _label_wrong if grid[14] == grid[17]
jmp _label_wrong if grid[15] == grid[16]
jmp _label_wrong if grid[15] == grid[17]
jmp _label_wrong if grid[16] == grid[17]
jmp _label_wrong if grid[18] == grid[19]
jmp _label_wrong if grid[18] == grid[20]
jmp _label_wrong if grid[18] == grid[21]
jmp _label_wrong if grid[18] == grid[22]
jmp _label_wrong if grid[18] == grid[23]
jmp _label_wrong if grid[18] == grid[24]
jmp _label_wrong if grid[18] == grid[25]
jmp _label_wrong if grid[18] == grid[26]
jmp _label_wrong if grid[19] == grid[20]
jmp _label_wrong if grid[19] == grid[21]
jmp _label_wrong if grid[19] == grid[22]
jmp _label_wrong if grid[19] == grid[23]
jmp _label_wrong if grid[19] == grid[24]
jmp _label_wrong if grid[19] == grid[25]
jmp _label_wrong if grid[19] == grid[26]
jmp _label_wrong if grid[20] == grid[21]
jmp _label_wrong if grid[20] == grid[22]
jmp _label_wrong if grid[20] == grid[23]
jmp _label_wrong if grid[20] == grid[24]
jmp _label_wrong if grid[20] == grid[25]
jmp _label_wrong if grid[20] == grid[26]
jmp _label_wrong if grid[21] == grid[22]
jmp _label_wrong if grid[21] == grid[23]
jmp _label_wrong if grid[21] == grid[24]
jmp _label_wrong if grid[21] == grid[25]
jmp _label_wrong if grid[21] == grid[26]
jmp _label_wrong if grid[22] == grid[23]
jmp _label_wrong if grid[22] == grid[24]
jmp _label_wrong if grid[22] == grid[25]
jmp _label_wrong if grid[22] == grid[26]
jmp _label_wrong if grid[23] == grid[24]
jmp _label_wrong if grid[23] == grid[25]
jmp _label_wrong if grid[23] == grid[26]
jmp _label_wrong if grid[24] == grid[25]
jmp _label_wrong if grid[24] == grid[26]
jmp _label_wrong if grid[25] == grid[26]
jmp _label_wrong if grid[27] == grid[28]
jmp _label_wrong if grid[27] == grid[29]
jmp _label_wrong if grid[27] == grid[30]
jmp _label_wrong if grid[27] == grid[31]
jmp _label_wrong if grid[27] == grid[32]
jmp _label_wrong if grid[27] == grid[33]
jmp _label_wrong if grid[27] == grid[34]
jmp _label_wrong if grid[27] == grid[35]
jmp _label_wrong if grid[28] == grid[29]
jmp _label_wrong if grid[28] == grid[30]
jmp _label_wrong if grid[28] == grid[31]
jmp _label_wrong if grid[28] == grid[32]
jmp _label_wrong if grid[28] == grid[33]
jmp _label_wrong if grid[28] == grid[34]
jmp _label_wrong if grid[28] == grid[35]
jmp _label_wrong if grid[29] == grid[30]
jmp _label_wrong if grid[29] == grid[31]
jmp _label_wrong if grid[29] == grid[32]
jmp _label_wrong if grid[29] == grid[33]
jmp _label_wrong if grid[29] == grid[34]
jmp _label_wrong if grid[29] == grid[35]
jmp _label_wrong if grid[30] == grid[31]
jmp _label_wrong if grid[30] == grid[32]
jmp _label_wrong if grid[30] == grid[33]
jmp _label_wrong if grid[30] == grid[34]
jmp _label_wrong if grid[30] == grid[35]
jmp _label_wrong if grid[31] == grid[32]
jmp _label_wrong if grid[31] == grid[33]
jmp _label_wrong if grid[31] == grid[34]
jmp _label_wrong if grid[31] == grid[35]
jmp _label_wrong if grid[32] == grid[33]
jmp _label_wrong if grid[32] == grid[34]
jmp _label_wrong if grid[32] == grid[35]
jmp _label_wrong if grid[33] == grid[34]
jmp _label_wrong if grid[33] == grid[35]
jmp _label_wrong if grid[34] == grid[35]
jmp _label_wrong if grid[36] == grid[37]
jmp _label_wrong if grid[36] == grid[38]
jmp _label_wrong if grid[36] == grid[39]
jmp _label_wrong if grid[36] == grid[40]
jmp _label_wrong if grid[36] == grid[41]
jmp _label_wrong if grid[36] == grid[42]
jmp _label_wrong if grid[36] == grid[43]
jmp _label_wrong if grid[36] == grid[44]
jmp _label_wrong if grid[37] == grid[38]
jmp _label_wrong if grid[37] == grid[39]
jmp _label_wrong if grid[37] == grid[40]
jmp _label_wrong if grid[37] == grid[41]
jmp _label_wrong if grid[37] == grid[42]
jmp _label_wrong if grid[37] == grid[43]
jmp _label_wrong if grid[37] == grid[44]
jmp _label_wrong if grid[38] == grid[39]
jmp _label_wrong if grid[38] == grid[40]
jmp _label_wrong if grid[38] == grid[41]
jmp _label_wrong if grid[38] == grid[42]
jmp _label_wrong if grid[38] == grid[43]
jmp _label_wrong if grid[38] == grid[44]
jmp _label_wrong if grid[39] == grid[40]
jmp _label_wrong if grid[39] == grid[41]
jmp _label_wrong if grid[39] == grid[42]
jmp _label_wrong if grid[39] == grid[43]
jmp _label_wrong if grid[39] == grid[44]
jmp _label_wrong if grid[40] == grid[41]
jmp _label_wrong if grid[40] == grid[42]
jmp _label_wrong if grid[40] == grid[43]
jmp _label_wrong if grid[40] == grid[44]
jmp _label_wrong if grid[41] == grid[42]
jmp _label_wrong if grid[41] == grid[43]
jmp _label_wrong if grid[41] == grid[44]
jmp _label_wrong if grid[42] == grid[43]
jmp _label_wrong if grid[42] == grid[44]
jmp _label_wrong if grid[43] == grid[44]
jmp _label_wrong if grid[45] == grid[46]
jmp _label_wrong if grid[45] == grid[47]
jmp _label_wrong if grid[45] == grid[48]
jmp _label_wrong if grid[45] == grid[49]
jmp _label_wrong if grid[45] == grid[50]
jmp _label_wrong if grid[45] == grid[51]
jmp _label_wrong if grid[45] == grid[52]
jmp _label_wrong if grid[45] == grid[53]
jmp _label_wrong if grid[46] == grid[47]
jmp _label_wrong if grid[46] == grid[48]
jmp _label_wrong if grid[46] == grid[49]
jmp _label_wrong if grid[46] == grid[50]
jmp _label_wrong if grid[46] == grid[51]
jmp _label_wrong if grid[46] == grid[52]
jmp _label_wrong if grid[46] == grid[53]
jmp _label_wrong if grid[47] == grid[48]
jmp _label_wrong if grid[47] == grid[49]
jmp _label_wrong if grid[47] == grid[50]
jmp _label_wrong if grid[47] == grid[51]
jmp _label_wrong if grid[47] == grid[52]
jmp _label_wrong if grid[47] == grid[53]
jmp _label_wrong if grid[48] == grid[49]
jmp _label_wrong if grid[48] == grid[50]
jmp _label_wrong if grid[48] == grid[51]
jmp _label_wrong if grid[48] == grid[52]
jmp _label_wrong if grid[48] == grid[53]
jmp _label_wrong if grid[49] == grid[50]
jmp _label_wrong if grid[49] == grid[51]
jmp _label_wrong if grid[49] == grid[52]
jmp _label_wrong if grid[49] == grid[53]
jmp _label_wrong if grid[50] == grid[51]
jmp _label_wrong if grid[50] == grid[52]
jmp _label_wrong if grid[50] == grid[53]
jmp _label_wrong if grid[51] == grid[52]
jmp _label_wrong if grid[51] == grid[53]
jmp _label_wrong if grid[52] == grid[53]
jmp _label_wrong if grid[54] == grid[55]
jmp _label_wrong if grid[54] == grid[56]
jmp _label_wrong if grid[54] == grid[57]
jmp _label_wrong if grid[54] == grid[58]
jmp _label_wrong if grid[54] == grid[59]
jmp _label_wrong if grid[54] == grid[60]
jmp _label_wrong if grid[54] == grid[61]
jmp _label_wrong if grid[54] == grid[62]
jmp _label_wrong if grid[55] == grid[56]
jmp _label_wrong if grid[55] == grid[57]
jmp _label_wrong if grid[55] == grid[58]
jmp _label_wrong if grid[55] == grid[59]
jmp _label_wrong if grid[55] == grid[60]
jmp _label_wrong if grid[55] == grid[61]
jmp _label_wrong if grid[55] == grid[62]
jmp _label_wrong if grid[56] == grid[57]
jmp _label_wrong if grid[56] == grid[58]
jmp _label_wrong if grid[56] == grid[59]
jmp _label_wrong if grid[56] == grid[60]
jmp _label_wrong if grid[56] == grid[61]
jmp _label_wrong if grid[56] == grid[62]
jmp _label_wrong if grid[57] == grid[58]
jmp _label_wrong if grid[57] == grid[59]
jmp _label_wrong if grid[57] == grid[60]
jmp _label_wrong if grid[57] == grid[61]
jmp _label_wrong if grid[57] == grid[62]
jmp _label_wrong if grid[58] == grid[59]
jmp _label_wrong if grid[58] == grid[60]
jmp _label_wrong if grid[58] == grid[61]
jmp _label_wrong if grid[58] == grid[62]
jmp _label_wrong if grid[59] == grid[60]
jmp _label_wrong if grid[59] == grid[61]
jmp _label_wrong if grid[59] == grid[62]
jmp _label_wrong if grid[60] == grid[61]
jmp _label_wrong if grid[60] == grid[62]
jmp _label_wrong if grid[61] == grid[62]
jmp _label_wrong if grid[63] == grid[64]
jmp _label_wrong if grid[63] == grid[65]
jmp _label_wrong if grid[63] == grid[66]
jmp _label_wrong if grid[63] == grid[67]
jmp _label_wrong if grid[63] == grid[68]
jmp _label_wrong if grid[63] == grid[69]
jmp _label_wrong if grid[63] == grid[70]
jmp _label_wrong if grid[63] == grid[71]
jmp _label_wrong if grid[64] == grid[65]
jmp _label_wrong if grid[64] == grid[66]
jmp _label_wrong if grid[64] == grid[67]
jmp _label_wrong if grid[64] == grid[68]
jmp _label_wrong if grid[64] == grid[69]
jmp _label_wrong if grid[64] == grid[70]
jmp _label_wrong if grid[64] == grid[71]
jmp _label_wrong if grid[65] == grid[66]
jmp _label_wrong if grid[65] == grid[67]
jmp _label_wrong if grid[65] == grid[68]
jmp _label_wrong if grid[65] == grid[69]
jmp _label_wrong if grid[65] == grid[70]
jmp _label_wrong if grid[65] == grid[71]
jmp _label_wrong if grid[66] == grid[67]
jmp _label_wrong if grid[66] == grid[68]
jmp _label_wrong if grid[66] == grid[69]
jmp _label_wrong if grid[66] == grid[70]
jmp _label_wrong if grid[66] == grid[71]
jmp _label_wrong if grid[67] == grid[68]
jmp _label_wrong if grid[67] == grid[69]
jmp _label_wrong if grid[67] == grid[70]
jmp _label_wrong if grid[67] == grid[71]
jmp _label_wrong if grid[68] == grid[69]
jmp _label_wrong if grid[68] == grid[70]
jmp _label_wrong if grid[68] == grid[71]
jmp _label_wrong if grid[69] == grid[70]
jmp _label_wrong if grid[69] == grid[71]
jmp _label_wrong if grid[70] == grid[71]
jmp _label_wrong if grid[72] == grid[73]
jmp _label_wrong if grid[72] == grid[74]
jmp _label_wrong if grid[72] == grid[75]
jmp _label_wrong if grid[72] == grid[76]
jmp _label_wrong if grid[72] == grid[77]
jmp _label_wrong if grid[72] == grid[78]
jmp _label_wrong if grid[72] == grid[79]
jmp _label_wrong if grid[72] == grid[80]
jmp _label_wrong if grid[73] == grid[74]
jmp _label_wrong if grid[73] == grid[75]
jmp _label_wrong if grid[73] == grid[76]
jmp _label_wrong if grid[73] == grid[77]
jmp _label_wrong if grid[73] == grid[78]
jmp _label_wrong if grid[73] == grid[79]
jmp _label_wrong if grid[73] == grid[80]
jmp _label_wrong if grid[74] == grid[75]
jmp _label_wrong if grid[74] == grid[76]
jmp _label_wrong if grid[74] == grid[77]
jmp _label_wrong if grid[74] == grid[78]
jmp _label_wrong if grid[74] == grid[79]
jmp _label_wrong if grid[74] == grid[80]
jmp _label_wrong if grid[75] == grid[76]
jmp _label_wrong if grid[75] == grid[77]
jmp _label_wrong if grid[75] == grid[78]
jmp _label_wrong if grid[75] == grid[79]
jmp _label_wrong if grid[75] == grid[80]
jmp _label_wrong if grid[76] == grid[77]
jmp _label_wrong if grid[76] == grid[78]
jmp _label_wrong if grid[76] == grid[79]
jmp _label_wrong if grid[76] == grid[80]
jmp _label_wrong if grid[77] == grid[78]
jmp _label_wrong if grid[77] == grid[79]
jmp _label_wrong if grid[77] == grid[80]
jmp _label_wrong if grid[78] == grid[79]
jmp _label_wrong if grid[78] == grid[80]
jmp _label_wrong if grid[79] == grid[80]
jmp _label_wrong if grid[0] == grid[1]
jmp _label_wrong if grid[0] == grid[2]
jmp _label_wrong if grid[0] == grid[3]
jmp _label_wrong if grid[0] == grid[4]
jmp _label_wrong if grid[0] == grid[5]
jmp _label_wrong if grid[0] == grid[6]
jmp _label_wrong if grid[0] == grid[7]
jmp _label_wrong if grid[0] == grid[8]
jmp _label_wrong if grid[1] == grid[2]
jmp _label_wrong if grid[1] == grid[3]
jmp _label_wrong if grid[1] == grid[4]
jmp _label_wrong if grid[1] == grid[5]
jmp _label_wrong if grid[1] == grid[6]
jmp _label_wrong if grid[1] == grid[7]
jmp _label_wrong if grid[1] == grid[8]
jmp _label_wrong if grid[2] == grid[3]
jmp _label_wrong if grid[2] == grid[4]
jmp _label_wrong if grid[2] == grid[5]
jmp _label_wrong if grid[2] == grid[6]
jmp _label_wrong if grid[2] == grid[7]
jmp _label_wrong if grid[2] == grid[8]
jmp _label_wrong if grid[3] == grid[4]
jmp _label_wrong if grid[3] == grid[5]
jmp _label_wrong if grid[3] == grid[6]
jmp _label_wrong if grid[3] == grid[7]
jmp _label_wrong if grid[3] == grid[8]

// columns
jmp _label_wrong if grid[0] == grid[9]
jmp _label_wrong if grid[0] == grid[18]
jmp _label_wrong if grid[0] == grid[27]
jmp _label_wrong if grid[0] == grid[36]
jmp _label_wrong if grid[0] == grid[45]
jmp _label_wrong if grid[0] == grid[54]
jmp _label_wrong if grid[0] == grid[63]
jmp _label_wrong if grid[0] == grid[72]
jmp _label_wrong if grid[9] == grid[18]
jmp _label_wrong if grid[9] == grid[27]
jmp _label_wrong if grid[9] == grid[36]
jmp _label_wrong if grid[9] == grid[45]
jmp _label_wrong if grid[9] == grid[54]
jmp _label_wrong if grid[9] == grid[63]
jmp _label_wrong if grid[9] == grid[72]
jmp _label_wrong if grid[18] == grid[27]
jmp _label_wrong if grid[18] == grid[36]
jmp _label_wrong if grid[18] == grid[45]
jmp _label_wrong if grid[18] == grid[54]
jmp _label_wrong if grid[18] == grid[63]
jmp _label_wrong if grid[18] == grid[72]
jmp _label_wrong if grid[27] == grid[36]
jmp _label_wrong if grid[27] == grid[45]
jmp _label_wrong if grid[27] == grid[54]
jmp _label_wrong if grid[27] == grid[63]
jmp _label_wrong if grid[27] == grid[72]
jmp _label_wrong if grid[36] == grid[45]
jmp _label_wrong if grid[36] == grid[54]
jmp _label_wrong if grid[36] == grid[63]
jmp _label_wrong if grid[36] == grid[72]
jmp _label_wrong if grid[45] == grid[54]
jmp _label_wrong if grid[45] == grid[63]
jmp _label_wrong if grid[45] == grid[72]
jmp _label_wrong if grid[54] == grid[63]
jmp _label_wrong if grid[54] == grid[72]
jmp _label_wrong if grid[63] == grid[72]
jmp _label_wrong if grid[1] == grid[10]
jmp _label_wrong if grid[1] == grid[19]
jmp _label_wrong if grid[1] == grid[28]
jmp _label_wrong if grid[1] == grid[37]
jmp _label_wrong if grid[1] == grid[46]
jmp _label_wrong if grid[1] == grid[55]
jmp _label_wrong if grid[1] == grid[64]
jmp _label_wrong if grid[1] == grid[73]
jmp _label_wrong if grid[10] == grid[19]
jmp _label_wrong if grid[10] == grid[28]
jmp _label_wrong if grid[10] == grid[37]
jmp _label_wrong if grid[10] == grid[46]
jmp _label_wrong if grid[10] == grid[55]
jmp _label_wrong if grid[10] == grid[64]
jmp _label_wrong if grid[10] == grid[73]
jmp _label_wrong if grid[19] == grid[28]
jmp _label_wrong if grid[19] == grid[37]
jmp _label_wrong if grid[19] == grid[46]
jmp _label_wrong if grid[19] == grid[55]
jmp _label_wrong if grid[19] == grid[64]
jmp _label_wrong if grid[19] == grid[73]
jmp _label_wrong if grid[28] == grid[37]
jmp _label_wrong if grid[28] == grid[46]
jmp _label_wrong if grid[28] == grid[55]
jmp _label_wrong if grid[28] == grid[64]
jmp _label_wrong if grid[28] == grid[73]
jmp _label_wrong if grid[37] == grid[46]
jmp _label_wrong if grid[37] == grid[55]
jmp _label_wrong if grid[37] == grid[64]
jmp _label_wrong if grid[37] == grid[73]
jmp _label_wrong if grid[46] == grid[55]
jmp _label_wrong if grid[46] == grid[64]
jmp _label_wrong if grid[46] == grid[73]
jmp _label_wrong if grid[55] == grid[64]
jmp _label_wrong if grid[55] == grid[73]
jmp _label_wrong if grid[64] == grid[73]
jmp _label_wrong if grid[2] == grid[11]
jmp _label_wrong if grid[2] == grid[20]
jmp _label_wrong if grid[2] == grid[29]
jmp _label_wrong if grid[2] == grid[38]
jmp _label_wrong if grid[2] == grid[47]
jmp _label_wrong if grid[2] == grid[56]
jmp _label_wrong if grid[2] == grid[65]
jmp _label_wrong if grid[2] == grid[74]
jmp _label_wrong if grid[11] == grid[20]
jmp _label_wrong if grid[11] == grid[29]
jmp _label_wrong if grid[11] == grid[38]
jmp _label_wrong if grid[11] == grid[47]
jmp _label_wrong if grid[11] == grid[56]
jmp _label_wrong if grid[11] == grid[65]
jmp _label_wrong if grid[11] == grid[74]
jmp _label_wrong if grid[20] == grid[29]
jmp _label_wrong if grid[20] == grid[38]
jmp _label_wrong if grid[20] == grid[47]
jmp _label_wrong if grid[20] == grid[56]
jmp _label_wrong if grid[20] == grid[65]
jmp _label_wrong if grid[20] == grid[74]
jmp _label_wrong if grid[29] == grid[38]
jmp _label_wrong if grid[29] == grid[47]
jmp _label_wrong if grid[29] == grid[56]
jmp _label_wrong if grid[29] == grid[65]
jmp _label_wrong if grid[29] == grid[74]
jmp _label_wrong if grid[38] == grid[47]
jmp _label_wrong if grid[38] == grid[56]
jmp _label_wrong if grid[38] == grid[65]
jmp _label_wrong if grid[38] == grid[74]
jmp _label_wrong if grid[47] == grid[56]
jmp _label_wrong if grid[47] == grid[65]
jmp _label_wrong if grid[47] == grid[74]
jmp _label_wrong if grid[56] == grid[65]
jmp _label_wrong if grid[56] == grid[74]
jmp _label_wrong if grid[65] == grid[74]
jmp _label_wrong if grid[3] == grid[12]
jmp _label_wrong if grid[3] == grid[21]
jmp _label_wrong if grid[3] == grid[30]
jmp _label_wrong if grid[3] == grid[39]
jmp _label_wrong if grid[3] == grid[48]
jmp _label_wrong if grid[3] == grid[57]
jmp _label_wrong if grid[3] == grid[66]
jmp _label_wrong if grid[3] == grid[75]
jmp _label_wrong if grid[12] == grid[21]
jmp _label_wrong if grid[12] == grid[30]
jmp _label_wrong if grid[12] == grid[39]
jmp _label_wrong if grid[12] == grid[48]
jmp _label_wrong if grid[12] == grid[57]
jmp _label_wrong if grid[12] == grid[66]
jmp _label_wrong if grid[12] == grid[75]
jmp _label_wrong if grid[21] == grid[30]
jmp _label_wrong if grid[21] == grid[39]
jmp _label_wrong if grid[21] == grid[48]
jmp _label_wrong if grid[21] == grid[57]
jmp _label_wrong if grid[21] == grid[66]
jmp _label_wrong if grid[21] == grid[75]
jmp _label_wrong if grid[30] == grid[39]
jmp _label_wrong if grid[30] == grid[48]
jmp _label_wrong if grid[30] == grid[57]
jmp _label_wrong if grid[30] == grid[66]
jmp _label_wrong if grid[30] == grid[75]
jmp _label_wrong if grid[39] == grid[48]
jmp _label_wrong if grid[39] == grid[57]
jmp _label_wrong if grid[39] == grid[66]
jmp _label_wrong if grid[39] == grid[75]
jmp _label_wrong if grid[48] == grid[57]
jmp _label_wrong if grid[48] == grid[66]
jmp _label_wrong if grid[48] == grid[75]
jmp _label_wrong if grid[57] == grid[66]
jmp _label_wrong if grid[57] == grid[75]
jmp _label_wrong if grid[66] == grid[75]
jmp _label_wrong if grid[4] == grid[13]
jmp _label_wrong if grid[4] == grid[22]
jmp _label_wrong if grid[4] == grid[31]
jmp _label_wrong if grid[4] == grid[40]
jmp _label_wrong if grid[4] == grid[49]
jmp _label_wrong if grid[4] == grid[58]
jmp _label_wrong if grid[4] == grid[67]
jmp _label_wrong if grid[4] == grid[76]
jmp _label_wrong if grid[13] == grid[22]
jmp _label_wrong if grid[13] == grid[31]
jmp _label_wrong if grid[13] == grid[40]
jmp _label_wrong if grid[13] == grid[49]
jmp _label_wrong if grid[13] == grid[58]
jmp _label_wrong if grid[13] == grid[67]
jmp _label_wrong if grid[13] == grid[76]
jmp _label_wrong if grid[22] == grid[31]
jmp _label_wrong if grid[22] == grid[40]
jmp _label_wrong if grid[22] == grid[49]
jmp _label_wrong if grid[22] == grid[58]
jmp _label_wrong if grid[22] == grid[67]
jmp _label_wrong if grid[22] == grid[76]
jmp _label_wrong if grid[31] == grid[40]
jmp _label_wrong if grid[31] == grid[49]
jmp _label_wrong if grid[31] == grid[58]
jmp _label_wrong if grid[31] == grid[67]
jmp _label_wrong if grid[31] == grid[76]
jmp _label_wrong if grid[40] == grid[49]
jmp _label_wrong if grid[40] == grid[58]
jmp _label_wrong if grid[40] == grid[67]
jmp _label_wrong if grid[40] == grid[76]
jmp _label_wrong if grid[49] == grid[58]
jmp _label_wrong if grid[49] == grid[67]
jmp _label_wrong if grid[49] == grid[76]
jmp _label_wrong if grid[58] == grid[67]
jmp _label_wrong if grid[58] == grid[76]
jmp _label_wrong if grid[67] == grid[76]
jmp _label_wrong if grid[5] == grid[14]
jmp _label_wrong if grid[5] == grid[23]
jmp _label_wrong if grid[5] == grid[32]
jmp _label_wrong if grid[5] == grid[41]
jmp _label_wrong if grid[5] == grid[50]
jmp _label_wrong if grid[5] == grid[59]
jmp _label_wrong if grid[5] == grid[68]
jmp _label_wrong if grid[5] == grid[77]
jmp _label_wrong if grid[14] == grid[23]
jmp _label_wrong if grid[14] == grid[32]
jmp _label_wrong if grid[14] == grid[41]
jmp _label_wrong if grid[14] == grid[50]
jmp _label_wrong if grid[14] == grid[59]
jmp _label_wrong if grid[14] == grid[68]
jmp _label_wrong if grid[14] == grid[77]
jmp _label_wrong if grid[23] == grid[32]
jmp _label_wrong if grid[23] == grid[41]
jmp _label_wrong if grid[23] == grid[50]
jmp _label_wrong if grid[23] == grid[59]
jmp _label_wrong if grid[23] == grid[68]
jmp _label_wrong if grid[23] == grid[77]
jmp _label_wrong if grid[32] == grid[41]
jmp _label_wrong if grid[32] == grid[50]
jmp _label_wrong if grid[32] == grid[59]
jmp _label_wrong if grid[32] == grid[68]
jmp _label_wrong if grid[32] == grid[77]
jmp _label_wrong if grid[41] == grid[50]
jmp _label_wrong if grid[41] == grid[59]
jmp _label_wrong if grid[41] == grid[68]
jmp _label_wrong if grid[41] == grid[77]
jmp _label_wrong if grid[50] == grid[59]
jmp _label_wrong if grid[50] == grid[68]
jmp _label_wrong if grid[50] == grid[77]
jmp _label_wrong if grid[59] == grid[68]
jmp _label_wrong if grid[59] == grid[77]
jmp _label_wrong if grid[68] == grid[77]
jmp _label_wrong if grid[6] == grid[15]
jmp _label_wrong if grid[6] == grid[24]
jmp _label_wrong if grid[6] == grid[33]
jmp _label_wrong if grid[6] == grid[42]
jmp _label_wrong if grid[6] == grid[51]
jmp _label_wrong if grid[6] == grid[60]
jmp _label_wrong if grid[6] == grid[69]
jmp _label_wrong if grid[6] == grid[78]
jmp _label_wrong if grid[15] == grid[24]
jmp _label_wrong if grid[15] == grid[33]
jmp _label_wrong if grid[15] == grid[42]
jmp _label_wrong if grid[15] == grid[51]
jmp _label_wrong if grid[15] == grid[60]
jmp _label_wrong if grid[15] == grid[69]
jmp _label_wrong if grid[15] == grid[78]
jmp _label_wrong if grid[24] == grid[33]
jmp _label_wrong if grid[24] == grid[42]
jmp _label_wrong if grid[24] == grid[51]
jmp _label_wrong if grid[24] == grid[60]
jmp _label_wrong if grid[24] == grid[69]
jmp _label_wrong if grid[24] == grid[78]
jmp _label_wrong if grid[33] == grid[42]
jmp _label_wrong if grid[33] == grid[51]
jmp _label_wrong if grid[33] == grid[60]
jmp _label_wrong if grid[33] == grid[69]
jmp _label_wrong if grid[33] == grid[78]
jmp _label_wrong if grid[42] == grid[51]
jmp _label_wrong if grid[42] == grid[60]
jmp _label_wrong if grid[42] == grid[69]
jmp _label_wrong if grid[42] == grid[78]
jmp _label_wrong if grid[51] == grid[60]
jmp _label_wrong if grid[51] == grid[69]
jmp _label_wrong if grid[51] == grid[78]
jmp _label_wrong if grid[60] == grid[69]
jmp _label_wrong if grid[60] == grid[78]
jmp _label_wrong if grid[69] == grid[78]
jmp _label_wrong if grid[7] == grid[16]
jmp _label_wrong if grid[7] == grid[25]
jmp _label_wrong if grid[7] == grid[34]
jmp _label_wrong if grid[7] == grid[43]
jmp _label_wrong if grid[7] == grid[52]
jmp _label_wrong if grid[7] == grid[61]
jmp _label_wrong if grid[7] == grid[70]
jmp _label_wrong if grid[7] == grid[79]
jmp _label_wrong if grid[16] == grid[25]
jmp _label_wrong if grid[16] == grid[34]
jmp _label_wrong if grid[16] == grid[43]
jmp _label_wrong if grid[16] == grid[52]
jmp _label_wrong if grid[16] == grid[61]
jmp _label_wrong if grid[16] == grid[70]
jmp _label_wrong if grid[16] == grid[79]
jmp _label_wrong if grid[25] == grid[34]
jmp _label_wrong if grid[25] == grid[43]
jmp _label_wrong if grid[25] == grid[52]
jmp _label_wrong if grid[25] == grid[61]
jmp _label_wrong if grid[25] == grid[70]
jmp _label_wrong if grid[25] == grid[79]
jmp _label_wrong if grid[34] == grid[43]
jmp _label_wrong if grid[34] == grid[52]
jmp _label_wrong if grid[34] == grid[61]
jmp _label_wrong if grid[34] == grid[70]
jmp _label_wrong if grid[34] == grid[79]
jmp _label_wrong if grid[43] == grid[52]
jmp _label_wrong if grid[43] == grid[61]
jmp _label_wrong if grid[43] == grid[70]
jmp _label_wrong if grid[43] == grid[79]
jmp _label_wrong if grid[52] == grid[61]
jmp _label_wrong if grid[52] == grid[70]
jmp _label_wrong if grid[52] == grid[79]
jmp _label_wrong if grid[61] == grid[70]
jmp _label_wrong if grid[61] == grid[79]
jmp _label_wrong if grid[70] == grid[79]
jmp _label_wrong if grid[8] == grid[17]
jmp _label_wrong if grid[8] == grid[26]
jmp _label_wrong if grid[8] == grid[35]
jmp _label_wrong if grid[8] == grid[44]
jmp _label_wrong if grid[8] == grid[53]
jmp _label_wrong if grid[8] == grid[62]
jmp _label_wrong if grid[8] == grid[71]
jmp _label_wrong if grid[8] == grid[80]
jmp _label_wrong if grid[17] == grid[26]
jmp _label_wrong if grid[17] == grid[35]
jmp _label_wrong if grid[17] == grid[44]
jmp _label_wrong if grid[17] == grid[53]
jmp _label_wrong if grid[17] == grid[62]
jmp _label_wrong if grid[17] == grid[71]
jmp _label_wrong if grid[17] == grid[80]
jmp _label_wrong if grid[26] == grid[35]
jmp _label_wrong if grid[26] == grid[44]
jmp _label_wrong if grid[26] == grid[53]
jmp _label_wrong if grid[26] == grid[62]
jmp _label_wrong if grid[26] == grid[71]
jmp _label_wrong if grid[26] == grid[80]
jmp _label_wrong if grid[35] == grid[44]
jmp _label_wrong if grid[35] == grid[53]
jmp _label_wrong if grid[35] == grid[62]
jmp _label_wrong if grid[35] == grid[71]
jmp _label_wrong if grid[35] == grid[80]
jmp _label_wrong if grid[44] == grid[53]
jmp _label_wrong if grid[44] == grid[62]
jmp _label_wrong if grid[44] == grid[71]
jmp _label_wrong if grid[44] == grid[80]
jmp _label_wrong if grid[53] == grid[62]
jmp _label_wrong if grid[53] == grid[71]
jmp _label_wrong if grid[53] == grid[80]
jmp _label_wrong if grid[62] == grid[71]
jmp _label_wrong if grid[62] == grid[80]
jmp _label_wrong if grid[71] == grid[80]
// subgrids
jmp _label_wrong if grid[0] == grid[1]
jmp _label_wrong if grid[0] == grid[2]
jmp _label_wrong if grid[0] == grid[9]
jmp _label_wrong if grid[0] == grid[10]
jmp _label_wrong if grid[0] == grid[11]
jmp _label_wrong if grid[0] == grid[18]
jmp _label_wrong if grid[0] == grid[19]
jmp _label_wrong if grid[0] == grid[20]
jmp _label_wrong if grid[1] == grid[2]
jmp _label_wrong if grid[1] == grid[9]
jmp _label_wrong if grid[1] == grid[10]
jmp _label_wrong if grid[1] == grid[11]
jmp _label_wrong if grid[1] == grid[18]
jmp _label_wrong if grid[1] == grid[19]
jmp _label_wrong if grid[1] == grid[20]
jmp _label_wrong if grid[2] == grid[9]
jmp _label_wrong if grid[2] == grid[10]
jmp _label_wrong if grid[2] == grid[11]
jmp _label_wrong if grid[2] == grid[18]
jmp _label_wrong if grid[2] == grid[19]
jmp _label_wrong if grid[2] == grid[20]
jmp _label_wrong if grid[9] == grid[10]
jmp _label_wrong if grid[9] == grid[11]
jmp _label_wrong if grid[9] == grid[18]
jmp _label_wrong if grid[9] == grid[19]
jmp _label_wrong if grid[9] == grid[20]
jmp _label_wrong if grid[10] == grid[11]
jmp _label_wrong if grid[10] == grid[18]
jmp _label_wrong if grid[10] == grid[19]
jmp _label_wrong if grid[10] == grid[20]
jmp _label_wrong if grid[11] == grid[18]
jmp _label_wrong if grid[11] == grid[19]
jmp _label_wrong if grid[11] == grid[20]
jmp _label_wrong if grid[18] == grid[19]
jmp _label_wrong if grid[18] == grid[20]
jmp _label_wrong if grid[19] == grid[20]
jmp _label_wrong if grid[3] == grid[4]
jmp _label_wrong if grid[3] == grid[5]
jmp _label_wrong if grid[3] == grid[12]
jmp _label_wrong if grid[3] == grid[13]
jmp _label_wrong if grid[3] == grid[14]
jmp _label_wrong if grid[3] == grid[21]
jmp _label_wrong if grid[3] == grid[22]
jmp _label_wrong if grid[3] == grid[23]
jmp _label_wrong if grid[4] == grid[5]
jmp _label_wrong if grid[4] == grid[12]
jmp _label_wrong if grid[4] == grid[13]
jmp _label_wrong if grid[4] == grid[14]
jmp _label_wrong if grid[4] == grid[21]
jmp _label_wrong if grid[4] == grid[22]
jmp _label_wrong if grid[4] == grid[23]
jmp _label_wrong if grid[5] == grid[12]
jmp _label_wrong if grid[5] == grid[13]
jmp _label_wrong if grid[5] == grid[14]
jmp _label_wrong if grid[5] == grid[21]
jmp _label_wrong if grid[5] == grid[22]
jmp _label_wrong if grid[5] == grid[23]
jmp _label_wrong if grid[12] == grid[13]
jmp _label_wrong if grid[12] == grid[14]
jmp _label_wrong if grid[12] == grid[21]
jmp _label_wrong if grid[12] == grid[22]
jmp _label_wrong if grid[12] == grid[23]
jmp _label_wrong if grid[13] == grid[14]
jmp _label_wrong if grid[13] == grid[21]
jmp _label_wrong if grid[13] == grid[22]
jmp _label_wrong if grid[13] == grid[23]
jmp _label_wrong if grid[14] == grid[21]
jmp _label_wrong if grid[14] == grid[22]
jmp _label_wrong if grid[14] == grid[23]
jmp _label_wrong if grid[21] == grid[22]
jmp _label_wrong if grid[21] == grid[23]
jmp _label_wrong if grid[22] == grid[23]
jmp _label_wrong if grid[6] == grid[7]
jmp _label_wrong if grid[6] == grid[8]
jmp _label_wrong if grid[6] == grid[15]
jmp _label_wrong if grid[6] == grid[16]
jmp _label_wrong if grid[6] == grid[17]
jmp _label_wrong if grid[6] == grid[24]
jmp _label_wrong if grid[6] == grid[25]
jmp _label_wrong if grid[6] == grid[26]
jmp _label_wrong if grid[7] == grid[8]
jmp _label_wrong if grid[7] == grid[15]
jmp _label_wrong if grid[7] == grid[16]
jmp _label_wrong if grid[7] == grid[17]
jmp _label_wrong if grid[7] == grid[24]
jmp _label_wrong if grid[7] == grid[25]
jmp _label_wrong if grid[7] == grid[26]
jmp _label_wrong if grid[8] == grid[15]
jmp _label_wrong if grid[8] == grid[16]
jmp _label_wrong if grid[8] == grid[17]
jmp _label_wrong if grid[8] == grid[24]
jmp _label_wrong if grid[8] == grid[25]
jmp _label_wrong if grid[8] == grid[26]
jmp _label_wrong if grid[15] == grid[16]
jmp _label_wrong if grid[15] == grid[17]
jmp _label_wrong if grid[15] == grid[24]
jmp _label_wrong if grid[15] == grid[25]
jmp _label_wrong if grid[15] == grid[26]
jmp _label_wrong if grid[16] == grid[17]
jmp _label_wrong if grid[16] == grid[24]
jmp _label_wrong if grid[16] == grid[25]
jmp _label_wrong if grid[16] == grid[26]
jmp _label_wrong if grid[17] == grid[24]
jmp _label_wrong if grid[17] == grid[25]
jmp _label_wrong if grid[17] == grid[26]
jmp _label_wrong if grid[24] == grid[25]
jmp _label_wrong if grid[24] == grid[26]
jmp _label_wrong if grid[25] == grid[26]
jmp _label_wrong if grid[27] == grid[28]
jmp _label_wrong if grid[27] == grid[29]
jmp _label_wrong if grid[27] == grid[36]
jmp _label_wrong if grid[27] == grid[37]
jmp _label_wrong if grid[27] == grid[38]
jmp _label_wrong if grid[27] == grid[45]
jmp _label_wrong if grid[27] == grid[46]
jmp _label_wrong if grid[27] == grid[47]
jmp _label_wrong if grid[28] == grid[29]
jmp _label_wrong if grid[28] == grid[36]
jmp _label_wrong if grid[28] == grid[37]
jmp _label_wrong if grid[28] == grid[38]
jmp _label_wrong if grid[28] == grid[45]
jmp _label_wrong if grid[28] == grid[46]
jmp _label_wrong if grid[28] == grid[47]
jmp _label_wrong if grid[29] == grid[36]
jmp _label_wrong if grid[29] == grid[37]
jmp _label_wrong if grid[29] == grid[38]
jmp _label_wrong if grid[29] == grid[45]
jmp _label_wrong if grid[29] == grid[46]
jmp _label_wrong if grid[29] == grid[47]
jmp _label_wrong if grid[36] == grid[37]
jmp _label_wrong if grid[36] == grid[38]
jmp _label_wrong if grid[36] == grid[45]
jmp _label_wrong if grid[36] == grid[46]
jmp _label_wrong if grid[36] == grid[47]
jmp _label_wrong if grid[37] == grid[38]
jmp _label_wrong if grid[37] == grid[45]
jmp _label_wrong if grid[37] == grid[46]
jmp _label_wrong if grid[37] == grid[47]
jmp _label_wrong if grid[38] == grid[45]
jmp _label_wrong if grid[38] == grid[46]
jmp _label_wrong if grid[38] == grid[47]
jmp _label_wrong if grid[45] == grid[46]
jmp _label_wrong if grid[45] == grid[47]
jmp _label_wrong if grid[46] == grid[47]
jmp _label_wrong if grid[30] == grid[31]
jmp _label_wrong if grid[30] == grid[32]
jmp _label_wrong if grid[30] == grid[39]
jmp _label_wrong if grid[30] == grid[40]
jmp _label_wrong if grid[30] == grid[41]
jmp _label_wrong if grid[30] == grid[48]
jmp _label_wrong if grid[30] == grid[49]
jmp _label_wrong if grid[30] == grid[50]
jmp _label_wrong if grid[31] == grid[32]
jmp _label_wrong if grid[31] == grid[39]
jmp _label_wrong if grid[31] == grid[40]
jmp _label_wrong if grid[31] == grid[41]
jmp _label_wrong if grid[31] == grid[48]
jmp _label_wrong if grid[31] == grid[49]
jmp _label_wrong if grid[31] == grid[50]
jmp _label_wrong if grid[32] == grid[39]
jmp _label_wrong if grid[32] == grid[40]
jmp _label_wrong if grid[32] == grid[41]
jmp _label_wrong if grid[32] == grid[48]
jmp _label_wrong if grid[32] == grid[49]
jmp _label_wrong if grid[32] == grid[50]
jmp _label_wrong if grid[39] == grid[40]
jmp _label_wrong if grid[39] == grid[41]
jmp _label_wrong if grid[39] == grid[48]
jmp _label_wrong if grid[39] == grid[49]
jmp _label_wrong if grid[39] == grid[50]
jmp _label_wrong if grid[40] == grid[41]
jmp _label_wrong if grid[40] == grid[48]
jmp _label_wrong if grid[40] == grid[49]
jmp _label_wrong if grid[40] == grid[50]
jmp _label_wrong if grid[41] == grid[48]
jmp _label_wrong if grid[41] == grid[49]
jmp _label_wrong if grid[41] == grid[50]
jmp _label_wrong if grid[48] == grid[49]
jmp _label_wrong if grid[48] == grid[50]
jmp _label_wrong if grid[49] == grid[50]
jmp _label_wrong if grid[33] == grid[34]
jmp _label_wrong if grid[33] == grid[35]
jmp _label_wrong if grid[33] == grid[42]
jmp _label_wrong if grid[33] == grid[43]
jmp _label_wrong if grid[33] == grid[44]
jmp _label_wrong if grid[33] == grid[51]
jmp _label_wrong if grid[33] == grid[52]
jmp _label_wrong if grid[33] == grid[53]
jmp _label_wrong if grid[34] == grid[35]
jmp _label_wrong if grid[34] == grid[42]
jmp _label_wrong if grid[34] == grid[43]
jmp _label_wrong if grid[34] == grid[44]
jmp _label_wrong if grid[34] == grid[51]
jmp _label_wrong if grid[34] == grid[52]
jmp _label_wrong if grid[34] == grid[53]
jmp _label_wrong if grid[35] == grid[42]
jmp _label_wrong if grid[35] == grid[43]
jmp _label_wrong if grid[35] == grid[44]
jmp _label_wrong if grid[35] == grid[51]
jmp _label_wrong if grid[35] == grid[52]
jmp _label_wrong if grid[35] == grid[53]
jmp _label_wrong if grid[42] == grid[43]
jmp _label_wrong if grid[42] == grid[44]
jmp _label_wrong if grid[42] == grid[51]
jmp _label_wrong if grid[42] == grid[52]
jmp _label_wrong if grid[42] == grid[53]
jmp _label_wrong if grid[43] == grid[44]
jmp _label_wrong if grid[43] == grid[51]
jmp _label_wrong if grid[43] == grid[52]
jmp _label_wrong if grid[43] == grid[53]
jmp _label_wrong if grid[44] == grid[51]
jmp _label_wrong if grid[44] == grid[52]
jmp _label_wrong if grid[44] == grid[53]
jmp _label_wrong if grid[51] == grid[52]
jmp _label_wrong if grid[51] == grid[53]
jmp _label_wrong if grid[52] == grid[53]
jmp _label_wrong if grid[54] == grid[55]
jmp _label_wrong if grid[54] == grid[56]
jmp _label_wrong if grid[54] == grid[63]
jmp _label_wrong if grid[54] == grid[64]
jmp _label_wrong if grid[54] == grid[65]
jmp _label_wrong if grid[54] == grid[72]
jmp _label_wrong if grid[54] == grid[73]
jmp _label_wrong if grid[54] == grid[74]
jmp _label_wrong if grid[55] == grid[56]
jmp _label_wrong if grid[55] == grid[63]
jmp _label_wrong if grid[55] == grid[64]
jmp _label_wrong if grid[55] == grid[65]
jmp _label_wrong if grid[55] == grid[72]
jmp _label_wrong if grid[55] == grid[73]
jmp _label_wrong if grid[55] == grid[74]
jmp _label_wrong if grid[56] == grid[63]
jmp _label_wrong if grid[56] == grid[64]
jmp _label_wrong if grid[56] == grid[65]
jmp _label_wrong if grid[56] == grid[72]
jmp _label_wrong if grid[56] == grid[73]
jmp _label_wrong if grid[56] == grid[74]
jmp _label_wrong if grid[63] == grid[64]
jmp _label_wrong if grid[63] == grid[65]
jmp _label_wrong if grid[63] == grid[72]
jmp _label_wrong if grid[63] == grid[73]
jmp _label_wrong if grid[63] == grid[74]
jmp _label_wrong if grid[64] == grid[65]
jmp _label_wrong if grid[64] == grid[72]
jmp _label_wrong if grid[64] == grid[73]
jmp _label_wrong if grid[64] == grid[74]
jmp _label_wrong if grid[65] == grid[72]
jmp _label_wrong if grid[65] == grid[73]
jmp _label_wrong if grid[65] == grid[74]
jmp _label_wrong if grid[72] == grid[73]
jmp _label_wrong if grid[72] == grid[74]
jmp _label_wrong if grid[73] == grid[74]
jmp _label_wrong if grid[57] == grid[58]
jmp _label_wrong if grid[57] == grid[59]
jmp _label_wrong if grid[57] == grid[66]
jmp _label_wrong if grid[57] == grid[67]
jmp _label_wrong if grid[57] == grid[68]
jmp _label_wrong if grid[57] == grid[75]
jmp _label_wrong if grid[57] == grid[76]
jmp _label_wrong if grid[57] == grid[77]
jmp _label_wrong if grid[58] == grid[59]
jmp _label_wrong if grid[58] == grid[66]
jmp _label_wrong if grid[58] == grid[67]
jmp _label_wrong if grid[58] == grid[68]
jmp _label_wrong if grid[58] == grid[75]
jmp _label_wrong if grid[58] == grid[76]
jmp _label_wrong if grid[58] == grid[77]
jmp _label_wrong if grid[59] == grid[66]
jmp _label_wrong if grid[59] == grid[67]
jmp _label_wrong if grid[59] == grid[68]
jmp _label_wrong if grid[59] == grid[75]
jmp _label_wrong if grid[59] == grid[76]
jmp _label_wrong if grid[59] == grid[77]
jmp _label_wrong if grid[66] == grid[67]
jmp _label_wrong if grid[66] == grid[68]
jmp _label_wrong if grid[66] == grid[75]
jmp _label_wrong if grid[66] == grid[76]
jmp _label_wrong if grid[66] == grid[77]
jmp _label_wrong if grid[67] == grid[68]
jmp _label_wrong if grid[67] == grid[75]
jmp _label_wrong if grid[67] == grid[76]
jmp _label_wrong if grid[67] == grid[77]
jmp _label_wrong if grid[68] == grid[75]
jmp _label_wrong if grid[68] == grid[76]
jmp _label_wrong if grid[68] == grid[77]
jmp _label_wrong if grid[75] == grid[76]
jmp _label_wrong if grid[75] == grid[77]
jmp _label_wrong if grid[76] == grid[77]
jmp _label_wrong if grid[60] == grid[61]
jmp _label_wrong if grid[60] == grid[62]
jmp _label_wrong if grid[60] == grid[69]
jmp _label_wrong if grid[60] == grid[70]
jmp _label_wrong if grid[60] == grid[71]
jmp _label_wrong if grid[60] == grid[78]
jmp _label_wrong if grid[60] == grid[79]
jmp _label_wrong if grid[60] == grid[80]
jmp _label_wrong if grid[61] == grid[62]
jmp _label_wrong if grid[61] == grid[69]
jmp _label_wrong if grid[61] == grid[70]
jmp _label_wrong if grid[61] == grid[71]
jmp _label_wrong if grid[61] == grid[78]
jmp _label_wrong if grid[61] == grid[79]
jmp _label_wrong if grid[61] == grid[80]
jmp _label_wrong if grid[62] == grid[69]
jmp _label_wrong if grid[62] == grid[70]
jmp _label_wrong if grid[62] == grid[71]
jmp _label_wrong if grid[62] == grid[78]
jmp _label_wrong if grid[62] == grid[79]
jmp _label_wrong if grid[62] == grid[80]
jmp _label_wrong if grid[69] == grid[70]
jmp _label_wrong if grid[69] == grid[71]
jmp _label_wrong if grid[69] == grid[78]
jmp _label_wrong if grid[69] == grid[79]
jmp _label_wrong if grid[69] == grid[80]
jmp _label_wrong if grid[70] == grid[71]
jmp _label_wrong if grid[70] == grid[78]
jmp _label_wrong if grid[70] == grid[79]
jmp _label_wrong if grid[70] == grid[80]
jmp _label_wrong if grid[71] == grid[78]
jmp _label_wrong if grid[71] == grid[79]
jmp _label_wrong if grid[71] == grid[80]
jmp _label_wrong if grid[78] == grid[79]
jmp _label_wrong if grid[78] == grid[80]
jmp _label_wrong if grid[79] == grid[80]

//check range

jmp _label_wrong if outofnumbers(grid[1])
jmp _label_wrong if outofnumbers(grid[2])
jmp _label_wrong if outofnumbers(grid[3])
jmp _label_wrong if outofnumbers(grid[4])
jmp _label_wrong if outofnumbers(grid[6])
jmp _label_wrong if outofnumbers(grid[7])
jmp _label_wrong if outofnumbers(grid[8])
jmp _label_wrong if outofnumbers(grid[11])
jmp _label_wrong if outofnumbers(grid[12])
jmp _label_wrong if outofnumbers(grid[13])
jmp _label_wrong if outofnumbers(grid[15])
jmp _label_wrong if outofnumbers(grid[18])
jmp _label_wrong if outofnumbers(grid[21])
jmp _label_wrong if outofnumbers(grid[22])
jmp _label_wrong if outofnumbers(grid[23])
jmp _label_wrong if outofnumbers(grid[24])
jmp _label_wrong if outofnumbers(grid[27])
jmp _label_wrong if outofnumbers(grid[30])
jmp _label_wrong if outofnumbers(grid[33])
jmp _label_wrong if outofnumbers(grid[34])
jmp _label_wrong if outofnumbers(grid[35])
jmp _label_wrong if outofnumbers(grid[36])
jmp _label_wrong if outofnumbers(grid[37])
jmp _label_wrong if outofnumbers(grid[38])
jmp _label_wrong if outofnumbers(grid[39])
jmp _label_wrong if outofnumbers(grid[41])
jmp _label_wrong if outofnumbers(grid[42])
jmp _label_wrong if outofnumbers(grid[43])
jmp _label_wrong if outofnumbers(grid[44])
jmp _label_wrong if outofnumbers(grid[45])
jmp _label_wrong if outofnumbers(grid[46])
jmp _label_wrong if outofnumbers(grid[47])
jmp _label_wrong if outofnumbers(grid[50])
jmp _label_wrong if outofnumbers(grid[53])
jmp _label_wrong if outofnumbers(grid[56])
jmp _label_wrong if outofnumbers(grid[57])
jmp _label_wrong if outofnumbers(grid[58])
jmp _label_wrong if outofnumbers(grid[59])
jmp _label_wrong if outofnumbers(grid[62])
jmp _label_wrong if outofnumbers(grid[65])
jmp _label_wrong if outofnumbers(grid[67])
jmp _label_wrong if outofnumbers(grid[68])
jmp _label_wrong if outofnumbers(grid[69])
jmp _label_wrong if outofnumbers(grid[72])
jmp _label_wrong if outofnumbers(grid[73])
jmp _label_wrong if outofnumbers(grid[74])
jmp _label_wrong if outofnumbers(grid[76])
jmp _label_wrong if outofnumbers(grid[77])
jmp _label_wrong if outofnumbers(grid[78])
jmp _label_wrong if outofnumbers(grid[79])


_label_correct:
print(correct)
return

_label_wrong:
print(wrong)
return


